import type { Metadata } from 'next';
import './globals.css';

import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

import Header from '@/modules/Header';
import Footer from '@/modules/Footer';
import ReactQueryProvider from '@/components/ReactQueryProvider';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'Restaurant (clone)',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className="bg-[url('/background.png')] bg-cover antialiased">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ReactQueryProvider>
            <Header />
            {children}
            <Footer />
            <Toaster position="top-center" />
          </ReactQueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
